# Generated by Django 3.1.3 on 2020-11-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_file',
            name='thumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='youtube_file',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='youtube_file',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
